---
application:
  name: "directus-api"
  project: "Agrigates"
  organization: "QoveryCommunity"
  storage:
    - name: "upload"
      size: "10"
      type: "fast_ssd"
      mount_point: "/mnt/upload"
databases:
  - type: "POSTGRESQL"
    name: "directus"
    version: "11.11.0"
routers:
  - name: "main-directus-api"
    routes:
      - application_name: "directus-api"
        paths:
          - "/*"
